services:

  db:
    image: postgres:17
    container_name: chat_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5435"
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5435
    networks:
      - db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chat_backend
    command: sh -c "uvicorn app:app --reload --host 0.0.0.0 --port 8005"
    ports: 
      - "8005:8005"
    volumes:
      - .:/app
    networks:
      - db-net
      - web-net
    env_file:
      - .env

volumes:
  postgres_data:
  # static_volume:
networks:
  db-net:
  web-net:
