"""chat messages: many-to-many logic

Revision ID: 20e2f34a4a08
Revises: 890d0ca43246
Create Date: 2024-12-11 18:37:26.918438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e2f34a4a08'
down_revision: Union[str, None] = '890d0ca43246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_users',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.add_column('chat', sa.Column('messages', sa.String(), nullable=True))
    op.drop_column('chat', 'message')
    op.alter_column('message', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('chat', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('chat', 'messages')
    op.drop_table('chat_users')
    # ### end Alembic commands ###
