"""Add sender and receiver to chat table

Revision ID: 37f3538fa040
Revises: 84a02fada451
Create Date: 2024-12-04 18:46:27.707910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f3538fa040'
down_revision: Union[str, None] = '84a02fada451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('chat', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('chat', sa.Column('message', sa.String(), nullable=False))
    op.drop_constraint('chat_users_id_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat', 'users_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_users_id_fkey', 'chat', 'users', ['users_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat', 'message')
    op.drop_column('chat', 'receiver_id')
    op.drop_column('chat', 'sender_id')
    # ### end Alembic commands ###
