"""Chat: messages relation with Message

Revision ID: 76e0f5a2c722
Revises: 34b47bf6f4b7
Create Date: 2024-12-11 19:09:06.839346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e0f5a2c722'
down_revision: Union[str, None] = '34b47bf6f4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('messages', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
