"""Chat: add default=0 to  unread_count column

Revision ID: 7acecb1aa351
Revises: b56b2aa84bdb
Create Date: 2025-01-07 20:38:57.543340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7acecb1aa351'
down_revision: Union[str, None] = 'b56b2aa84bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
