"""create users and chat tables once again

Revision ID: 7bc19fd5c3f1
Revises: 4e2630e52357
Create Date: 2024-12-01 16:47:25.146550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc19fd5c3f1'
down_revision: Union[str, None] = '4e2630e52357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
