"""user/chat relationship changes

Revision ID: 7c9ba997ff48
Revises: 4cf8b4677d34
Create Date: 2024-12-01 15:25:02.439668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9ba997ff48'
down_revision: Union[str, None] = '4cf8b4677d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
