"""Chat: add unread_count

Revision ID: b56b2aa84bdb
Revises: f794e8d264ea
Create Date: 2025-01-07 20:31:26.369651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56b2aa84bdb'
down_revision: Union[str, None] = 'f794e8d264ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('unread_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'unread_count')
    # ### end Alembic commands ###
