"""Chat: update messages relation with Message

Revision ID: d0820e37674e
Revises: 76e0f5a2c722
Create Date: 2024-12-11 19:11:17.422219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0820e37674e'
down_revision: Union[str, None] = '76e0f5a2c722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
