"""return back (uncommit) tables columns and relations after fixed alembic error

Revision ID: d9d23c4bf705
Revises: bf5ba9d6e2a4
Create Date: 2024-12-25 14:23:46.243447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d23c4bf705'
down_revision: Union[str, None] = 'bf5ba9d6e2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
